In [5]:
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(10, 5))
print(X)

[[-21.2277419    8.77498912  -1.40188999  -2.86228221  -6.09816276]
 [  6.70211581   0.2843024   -2.62850716  18.01114898 -17.30334532]
 [-17.26102837  15.00311038  11.35796853  -0.91743453   8.46505238]
 [-16.6401613   -8.38893703  16.41788885 -16.99793594  -4.03625553]
 [ -7.65315881  -1.42608232  12.72685282  -1.97904059  -0.0946943 ]
 [ -0.73244133   8.34211218 -11.9865029  -13.92842344   5.10638841]
 [ 21.04602378  20.14324755  15.28640107 -10.91364718   3.3953476 ]
 [ -3.13391153  -1.13629722  13.49330051 -10.54201644   4.91397346]
 [-10.30968028  -2.69232917   8.29240052  -1.51223816  -3.43812949]
 [  7.8881472  -13.26305887   5.76754179  -3.66855163   4.18170746]]


In [6]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(m)
print (X_norm)

[-4.13218367  2.5641057   6.7325454  -4.53104211 -0.49081181]
[[-1.36004949  0.63106678 -0.9224792   0.17984595 -0.78273442]
 [ 0.86193052 -0.23164308 -1.06158274  2.42942187 -2.34687445]
 [-1.04447473  1.26388505  0.52454244  0.38944649  1.25015595]
 [-0.9950812  -1.1129015   1.09835869 -1.34358476 -0.49491121]
 [-0.28011372 -0.40542946  0.67977968  0.27503486  0.05529435]
 [ 0.27046896  0.58708363 -2.12281883 -1.0127766   0.78131747]
 [ 2.00307049  1.78615694  0.97004322 -0.68786749  0.54247197]
 [ 0.07941826 -0.37598538  0.76669807 -0.64781602  0.75445812]
 [-0.49145521 -0.53408851  0.17689413  0.32534319 -0.41141834]
 [ 0.95628611 -1.60814448 -0.10943547  0.09295251  0.65224055]]


In [7]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [8]:
a=Z.sum(1)
b=a-10
print(a)
print(b)


[ 9 13  7  9 27 12]
[-1  3 -3 -1 17  2]


In [11]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [12]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)
AB=np.vstack((A,B))
AB


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
import pandas
data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data[:10]
data.head()


Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

In [25]:
a=np.arange(4)
b=np.arange(0,8,2)
print(a,b)
c=np.column_stack((a,b))
print(c)
d=np.vstack((a,b))
print(d)

[0 1 2 3] [0 2 4 6]
[[0 0]
 [1 2]
 [2 4]
 [3 6]]
[[0 1 2 3]
 [0 2 4 6]]


In [31]:
data[data.Sex=='female'].Name

PassengerId
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                   Nasser, Mrs. Nicholas (Adele Achem)
11                       Sandstrom, Miss. Marguerite Rut
12                              Bonnell, Miss. Elizabeth
15                  Vestrom, Miss. Hulda Amanda Adolfina
16                      Hewlett, Mrs. (Mary D Kingcome) 
19     Vander Planke, Mrs. Julius (Emelia Maria Vande...
20                               Masselmani, Mrs. Fatima
23                           McGowan, Miss. Anna "Annie"
25                         Palsson, Miss. Torborg Danira
26     Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
29                         O'Dwyer, Miss. Ellen "Nellie"
32        Spencer, Mrs. William Augustus (Marie Eugenie)
33                              Glynn, Miss. Mary Agatha
39                 